// Educational annotations for each step in each act
export const annotations = {
  act1: {
    landing: {
      title: 'Subscription Landing Page',
      badge: 'CIT',
      description: 'The cardholder browses the merchant website and selects a subscription plan.',
      details: [
        'This is a Cardholder Initiated Transaction (CIT) — the cardholder is actively present and making a decision.',
        'The merchant must clearly indicate that card details will be stored for future recurring payments.',
        'Consent to store credentials is a regulatory requirement under PSD2/SCA and card scheme rules.',
      ],
      flags: [],
    },
    checkout: {
      title: 'Hosted Session — Card Collection',
      badge: 'CIT',
      description: 'Card details are collected securely using Mastercard Hosted Session.',
      details: [
        'Hosted Session renders card input fields in secure iframes hosted by Mastercard Gateway.',
        'Raw card data (PAN, CVV) NEVER touches the merchant server — it goes directly to the gateway.',
        'This reduces PCI DSS scope to SAQ-A (simplest compliance level).',
        'The merchant only receives a session ID that references the stored card data.',
        'PaymentSession.updateSessionFromForm() tokenizes the card data into the gateway session.',
      ],
      flags: [
        { key: 'Integration', value: 'Hosted Session (session.js)' },
        { key: 'PCI Scope', value: 'SAQ-A' },
        { key: 'Card Data Handling', value: 'Gateway-hosted iframes' },
      ],
    },
    threeds: {
      title: '3D Secure Authentication (3DS)',
      badge: 'CIT',
      description: 'The cardholder authenticates via 3DS / Strong Customer Authentication.',
      details: [
        '3DS is REQUIRED for Cardholder Initiated Transactions under PSD2/SCA regulations.',
        'The gateway initiates authentication with the card issuer (ACS).',
        'The issuer may request a "challenge" — an OTP, biometric, or password verification.',
        'If the issuer trusts the transaction, it may approve "frictionlessly" (no challenge).',
        'Authentication results are stored by the gateway and passed to the acquirer during authorization.',
      ],
      flags: [
        { key: 'apiOperation', value: 'INITIATE_AUTHENTICATION' },
        { key: 'authentication.channel', value: 'PAYER_BROWSER' },
        { key: 'authentication.purpose', value: 'PAYMENT_TRANSACTION' },
        { key: 'Cardholder Present', value: 'YES' },
        { key: '3DS Required', value: 'YES' },
      ],
    },
    authorize: {
      title: 'Authorization & Credential Storage (CIT)',
      badge: 'CIT',
      description: 'The payment is authorized and card credentials are stored for future use.',
      details: [
        'The AUTHORIZE operation charges the card with 3DS authentication results attached.',
        'credential-on-file is set to FIRST_STORED — this is the initial storage of credentials.',
        'The initiator is CARDHOLDER because the customer is present and initiated the payment.',
        'After successful authorization, the card is tokenized for future MIT use.',
        'The token replaces the raw card number — the merchant never stores the actual PAN.',
        'An agreement ID is established to link this CIT to future MIT transactions.',
      ],
      flags: [
        { key: 'apiOperation', value: 'AUTHORIZE' },
        { key: 'credentialOnFile', value: 'FIRST_STORED' },
        { key: 'initiator', value: 'CARDHOLDER' },
        { key: 'transaction.source', value: 'INTERNET' },
        { key: 'agreement.type', value: 'RECURRING' },
      ],
    },
    complete: {
      title: 'Subscription Active',
      badge: 'CIT',
      description: 'The CIT is complete. Credentials are stored and the agreement is established.',
      details: [
        'The cardholder has successfully subscribed and authenticated.',
        'A payment token has been securely stored for future recurring charges.',
        'The agreement between cardholder and merchant enables Merchant Initiated Transactions.',
        'This agreement is the legal basis for charging without the cardholder present in the future.',
        'The merchant can now process MIT recurring and unscheduled payments using the stored token.',
      ],
      flags: [
        { key: 'Token Stored', value: 'YES' },
        { key: 'Agreement Established', value: 'YES' },
        { key: 'Future MIT Enabled', value: 'YES' },
      ],
    },
  },
  act2: {
    intro: {
      title: 'Recurring MIT — Monthly Billing',
      badge: 'RECURRING',
      description: '30 days later, the merchant charges the stored card automatically.',
      details: [
        'This is a Merchant Initiated Transaction (MIT) — the cardholder is NOT present.',
        'No 3DS authentication is required because the merchant is initiating based on a prior agreement.',
        'The stored token from Act 1 is used instead of the actual card number.',
        'MIT recurring transactions are predictable, scheduled charges (e.g., monthly subscription).',
        'The card schemes and regulators allow this because consent was captured during the CIT.',
      ],
      flags: [
        { key: 'Cardholder Present', value: 'NO' },
        { key: '3DS Required', value: 'NO' },
        { key: 'credentialOnFile', value: 'SUBSEQUENT' },
        { key: 'initiator', value: 'MERCHANT' },
        { key: 'agreement.type', value: 'RECURRING' },
      ],
    },
    processing: {
      title: 'Processing Recurring Payment',
      badge: 'RECURRING',
      description: 'The gateway processes the MIT using the stored token.',
      details: [
        'The PAY operation uses the stored token — no session or card details needed.',
        'credentialOnFile is set to SUBSEQUENT — this is a follow-up to the original FIRST_STORED.',
        'The agreement.id links this MIT back to the original CIT consent.',
        'transaction.source is MERCHANT because the merchant initiated this charge.',
        'If the card has been replaced (e.g., re-issued), the network may update the token automatically.',
      ],
      flags: [
        { key: 'apiOperation', value: 'PAY' },
        { key: 'credentialOnFile', value: 'SUBSEQUENT' },
        { key: 'initiator', value: 'MERCHANT' },
        { key: 'transaction.source', value: 'MERCHANT' },
        { key: 'agreement.type', value: 'RECURRING' },
        { key: 'sourceOfFunds.type', value: 'CARD (token)' },
      ],
    },
    complete: {
      title: 'Recurring Payment Complete',
      badge: 'RECURRING',
      description: 'The monthly charge has been processed successfully without cardholder interaction.',
      details: [
        'The cardholder was never involved — this is the key difference from Act 1.',
        'No authentication challenge was presented.',
        'The token and agreement established in Act 1 made this possible.',
        'This pattern repeats every billing cycle for the life of the subscription.',
      ],
      flags: [],
    },
  },
  act3: {
    intro: {
      title: 'Unscheduled MIT — Event-Driven Charges',
      badge: 'UNSCHEDULED',
      description: 'The merchant processes charges triggered by events, not a regular schedule.',
      details: [
        'Unscheduled MITs are triggered by specific events rather than a recurring schedule.',
        'Examples: plan upgrades (prorated charges), no-show fees, penalty charges.',
        'Like recurring MIT, these use the stored token and require no cardholder presence.',
        'The key difference: agreement.type is UNSCHEDULED instead of RECURRING.',
        'The original CIT consent must have covered these types of charges.',
      ],
      flags: [
        { key: 'Cardholder Present', value: 'NO' },
        { key: '3DS Required', value: 'NO' },
        { key: 'credentialOnFile', value: 'SUBSEQUENT' },
        { key: 'initiator', value: 'MERCHANT' },
        { key: 'agreement.type', value: 'UNSCHEDULED' },
      ],
    },
    prorated: {
      title: 'Prorated Charge — Plan Upgrade',
      badge: 'UNSCHEDULED',
      description: 'A prorated charge is applied after the customer previously agreed to a plan change.',
      details: [
        'The customer upgraded their plan (this decision was made earlier).',
        'The merchant calculates the prorated amount for the remaining billing period.',
        'This is an unscheduled MIT because it is event-driven, not on a regular schedule.',
        'The original agreement from Act 1 covers this type of charge.',
      ],
      flags: [
        { key: 'apiOperation', value: 'PAY' },
        { key: 'credentialOnFile', value: 'SUBSEQUENT' },
        { key: 'agreement.type', value: 'UNSCHEDULED' },
        { key: 'Charge Type', value: 'Prorated (Plan Upgrade)' },
        { key: 'Amount', value: '$5.00' },
      ],
    },
    penalty: {
      title: 'No-Show / Penalty Charge',
      badge: 'UNSCHEDULED',
      description: 'A penalty charge is applied for a no-show or terms violation.',
      details: [
        'No-show and penalty charges are common in hospitality, travel, and service industries.',
        'The cardholder agreed to potential penalty charges during the original sign-up (Act 1).',
        'These are unscheduled because they depend on a specific event occurring.',
        'Industry regulations govern when and how much can be charged as a penalty.',
        'The transaction uses the same stored token and agreement from the original CIT.',
      ],
      flags: [
        { key: 'apiOperation', value: 'PAY' },
        { key: 'credentialOnFile', value: 'SUBSEQUENT' },
        { key: 'agreement.type', value: 'UNSCHEDULED' },
        { key: 'Charge Type', value: 'No-Show / Penalty' },
        { key: 'Amount', value: '$25.00' },
      ],
    },
  },
};

// Guide mode steps
export const guideSteps = {
  act1: [
    {
      id: 'landing',
      title: 'View Subscription Plan',
      instruction: 'Review the subscription plan details and click "Subscribe Now" to begin.',
      annotationKey: 'landing',
      interactive: false,
    },
    {
      id: 'checkout',
      title: 'Enter Card Details (Hosted Session)',
      instruction: 'Fill in your card details in the secure hosted fields, check the consent box, and click "Pay $9.99/month".',
      annotationKey: 'checkout',
      interactive: true,
    },
    {
      id: 'threeds',
      title: '3DS Authentication',
      instruction: 'Complete the 3D Secure challenge. This simulates the issuer verifying your identity.',
      annotationKey: 'threeds',
      interactive: true,
    },
    {
      id: 'authorize',
      title: 'Authorization & Token Storage',
      instruction: 'The payment is being authorized and your card is being tokenized for future use.',
      annotationKey: 'authorize',
      interactive: false,
    },
    {
      id: 'complete',
      title: 'Subscription Confirmed',
      instruction: 'Your subscription is active! The credential-on-file agreement is now established.',
      annotationKey: 'complete',
      interactive: false,
    },
  ],
  act2: [
    {
      id: 'intro',
      title: 'Recurring Billing Overview',
      instruction: 'This simulates an automatic monthly charge. Click "Simulate 30 Days Later" to trigger it.',
      annotationKey: 'intro',
      interactive: false,
    },
    {
      id: 'processing',
      title: 'Processing MIT Payment',
      instruction: 'Watch the payment process without any cardholder interaction or 3DS challenge.',
      annotationKey: 'processing',
      interactive: true,
    },
    {
      id: 'complete',
      title: 'Payment Complete',
      instruction: 'The recurring charge was processed using the stored token. No authentication needed.',
      annotationKey: 'complete',
      interactive: false,
    },
  ],
  act3: [
    {
      id: 'intro',
      title: 'Unscheduled Payments Overview',
      instruction: 'Learn about event-driven merchant-initiated charges.',
      annotationKey: 'intro',
      interactive: false,
    },
    {
      id: 'prorated',
      title: 'Prorated Charge',
      instruction: 'Click "Simulate Plan Upgrade" to see a prorated charge.',
      annotationKey: 'prorated',
      interactive: true,
    },
    {
      id: 'penalty',
      title: 'Penalty Charge',
      instruction: 'Click "Simulate Penalty Charge" to see a no-show/penalty charge.',
      annotationKey: 'penalty',
      interactive: true,
    },
  ],
};
